[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/",
    "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
holesky = "${HOLESKY_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
holesky = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

[profile.remapping]
"@openzeppelin/contracts/" = "lib/openzeppelin-contracts/contracts/"
"forge-std" = "lib/forge-std/src/"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
